### ISSUE TITLE
Does not work with bungeecord

### ISSUE THREAD

**Issue by EvanMcGregor** [ZombieStriker/PsudoCommands#5]
The plugin doesn’t work with bungeecord. Essentially I’m trying to do /psudoas @p server anarchy to send the closest player to anarchy.

**Comment by Geolykt** [comment]
Could you provide further context? Your wording is too vague. Does it throw an error, does something happen or doesn't anything happen at all?

**Comment by EvanMcGregor** [comment]
It literally won’t load with bungeecord. It just throws an error which you get when a plugin doesn’t work with bungeecord then doesn’t load.

**Comment by Geolykt** [comment]
Aha, provide the error. That helps a lot

**Comment by EvanMcGregor** [comment]
17:37:15 [WARNING] Error enabling plugin PsudoCommand
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:327)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more

**Comment by Geolykt** [comment]
Are we even sure that Bungee supports Bukkit plugins?
